#---------------------------------# 
#      trigger configuration      # 
#---------------------------------# 
trigger:
- master

#---------------------------------# 
#      environment configuration  # 
#---------------------------------# 
resources:
- repo: self
queue:
  name: Hosted VS2017
  demands: DotNetFramework

steps:
- task: PowerShell@1
  displayName: install
  inputs:
    scriptType: inlineScript
    inlineScript: |
     Install-Module -Name Pester -Repository PSGallery -MinimumVersion 4.2.0 -SkipPublisherCheck -Force -Scope CurrentUser
     
#---------------------------------# 
#      test configuration         # 
#---------------------------------# 
- task: PowerShell@1
  displayName: test
  inputs:
    scriptType: inlineScript
    inlineScript: |
     $testResultsFile = "./TestsResults.xml"
     $result = Invoke-Pester -OutputFormat NUnitXml -OutputFile $testResultsFile -PassThru
     if ($result.FailedCount -gt 0) { 
         throw "$($result.FailedCount) tests failed."
     }
     if ($result.PassedCount -eq 0) { 
         throw "No tests passed."
     }

- task: PublishTestResults@2
  displayName: publish-testresult
  inputs:
    testRunner: "NUnit"
    testResultsFiles: "./TestsResults.xml"

